name: awscli

on:
  push:
    branches:
      - main
    paths:
      - 'awscli/**'
      - 'packages/awscli-core/**'
      - 'package.json'

jobs:
  awscli:
    name: Execute some awscli invocations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: ./iam_access_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: List us-east-1 DHCP option set values w/ default json output
        uses: ./awscli
        with:
          cli-command: ec2
          cli-subcommand: describe-dhcp-options
          cli-parameters: --query DhcpOptions[0].DhcpConfigurations[*].Values[0].Value
          aws-region: us-east-1
      - name: Get network interface subnet ID
        id: net-int-subnet-id
        uses: ./awscli
        with:
          cli-command: ec2
          cli-subcommand: describe-network-interfaces
          cli-options: --output text
          cli-parameters: --query NetworkInterfaces[0].SubnetId
          aws-region: us-east-1
      - name: Describe interface subnet ID
        uses: ./awscli
        env:
          ACTIONS_RUNNER_DEBUG: true
        with:
          cli-command: ec2
          cli-subcommand: describe-subnets
          cli-parameters: --subnet-id ${{ steps.net-int-subnet-id.outputs.cli-output }} --query Subnets[*].Tags
          aws-region: us-east-1
