name: cloudfront_invalidate

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'cloudfront_invalidate/**'
      - 'package.json'
      - 'package-lock.json'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'cloudfront_invalidate/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloudfront-invalidate:
    name: Invalidate CloudFront cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: ./iam_access_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: CloudFront invalidation
        uses: ./cloudfront_invalidate
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: |
            /index.html
            /error.html
            /static/*
