name: 'CloudFront Invalidation'

on:
  push:
    branches:
      - master
    paths:
      - 'packages/cloudfront_invalidate/**'
      - 'package.json'

jobs:
  cloudfront-invalidate:
    name: Invalidate CloudFront cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: ./packages/iam_access_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: CloudFront invalidation
        uses: ./packages/cloudfront_invalidate
        with:
          distribution-id: EMKUWBIVAK6PF
          paths: |
            /index.html
            /error.html
            /static/*
