name: 'S3 Sync'

on:
  push:
    branches:
      - master
    paths:
      - 'packages/ecs_redeploy/**'
      - 'packages/awscli-core/**'
      - 'package.json'

  pull_request:
    branches:
      - master
    paths:
      - 'packages/ecs_redeploy/**'
      - 'packages/awscli-core/**'
      - 'package.json'

jobs:
  s3-sync:
    name: Redeploys ECS service
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: ./packages/iam_access_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: ECS Redeploy
        uses: ./packages/ecs_redeploy
        with:
          local-path: packages/ecs_redeploy/dist
          bucket-name: github-actions-028920223318-us-east-1
          path-prefix: my/new/prefix
          args: --delete
