name: 'IAM Credentials'

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'iam_access_credentials/**'
      - 'package.json'

jobs:
  s3-sync:
    name: Setup IAM access credentials
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: ./iam_access_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
