name: 'IAM Credentials'

on:
  push:
    branches:
      - master
    paths:
      - 'packages/iam_access_credentials/**'
      - 'package.json'

  pull_request:
    branches:
      - master
    paths:
      - 'packages/iam_access_credentials/**'
      - 'package.json'

jobs:
  s3-sync:
    name: Setup IAM access credentials
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: ./packages/iam_access_credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
